### ISSUE TITLE
event Location latitude and longitude fields are documented as [String] but are floats

### ISSUE THREAD

**Issue by jordanorelli** [FusionAuth/fusionauth-site#2111]
for example on this page: https://fusionauth.io/docs/v1/tech/events-webhooks/events/audit-log-create

the event's location is listed as follows:

> event.info.location.latitude [String] 

But the sample json is as follows:

```
{
  "event": {
    "auditLog": { ... },
    "createInstant": 1629141543064,
    "id": "29e3f639-649e-4a5c-bc4b-eec7f89ee20c",
    "info": {
      "ipAddress": "42.42.42.42",
      "location": {
        "city": "Denver",
        "country": "US",
        "displayString": "Denver, CO, US",
        "latitude": 39.73915,
        "longitude": -104.9847,
        "region": "CO"
      },
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36"
    },
    "type": "audit-log.create"
  }
}
```

the `event.info.location.latitude` and longitude fields are both floats. Or ... rather ... "number", since it's json.

**Comment by mooreds** [comment]
We don't really follow strict JSON in our documentation. While `number` is a valid JSON datatype, we want to be more precise if we can be (so that people consuming the webhook can process it more easily). These are all built from Java and we want to use those data types.

https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/java/io/fusionauth/domain/Location.java#L33 shows that it is a double.

We use a Double here as well:

```
$ grep -R 'Double' site/docs/v1/tech/apis/users.adoc 
site/docs/v1/tech/apis/users.adoc:[field]#logins``[x]``.location.latitude# [type]#[Double]# [since]#Available since 1.30.0#::
site/docs/v1/tech/apis/users.adoc:[field]#logins``[x]``.location.longitude# [type]#[Double]# [since]#Available since 1.30.0#::
```

So let's change it to `Double` rather than `String`.

**Comment by mark-robustelli** [comment]
Updated to commit in this commit 05bdb9704ba9927e2751800b13e81adc9d10cf8c

**Comment by mark-robustelli** [comment]
Updated in PR: https://github.com/FusionAuth/fusionauth-site/pull/2301
