### ISSUE TITLE
Update our fast path install instructions.

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-site#2610]
FastPath only installs ZIP now (not FA-Search and FA-App in deb and rpm)

Commit proves it 
- https://github.com/FusionAuth/fusionauth-install/commit/950b46af8cf285fb21458acb41c1dd6a4d7c8e10

Outdated doc
- https://fusionauth.io/docs/v1/tech/installation-guide/fast-path

**Comment by mooreds** [comment]
@mrudatsprint it's good to note which PR this issue was completed under (in this case, #2905 )

Also, no need to add 'content' to small fixes like this. The content label is intended for large pieces of content that will be useful for our newsletter (and published to an internal slack channel based on the label).
