### ISSUE TITLE
Integration of nyc.id IDP into FusionAuth

### ISSUE THREAD

**Issue by ekta-wi** [FusionAuth/fusionauth-site#31]
Hello,

I need to integrate nyc.id for my application using FusionAuth as the service provider. nyc.id needs the meta data of the service provider. I do not see any option in FusionAuth to download that.
Please guide on how nyc.id SAML IDP can be integrated through FusionAuth

**Comment by voidmain** [comment]
I looked at that website and it looks like it isn't a valid identity provider and it also looks like it hasn't been updated since 2018. They claim to provide identity to New York City residents, but I couldn't find any real information about that. I'm not certain you should trust that website or their SAML implementation.

Are you certain that nyc.id is legitimate?

**Comment by robotdan** [comment]
If you do attempt to integrate with this provider, once you configured the IdP in FusionAuth, you'll see a view icon on the configuration title.

If you click that you'll see the Integration details. This will include an SP metadata URL.

https://fusionauth.io/docs/v1/tech/identity-providers/samlv2/

**Comment by robotdan** [comment]
Closing this one out. If you have any particular issues remaining, please open them against the fusionauth-issues repo. Thanks!

https://github.com/FusionAuth/fusionauth-issues/issues
