### ISSUE TITLE
Google IdP doc is missing authorized domain configuration

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#6]
https://fusionauth.io/docs/v1/tech/identity-providers/google

Before the `Create a Google Identity Provider` section, we need to instruct the user to whitelist their domain. 

<img width="748" alt="Screen Shot 2019-05-02 at 9 38 20 AM" src="https://user-images.githubusercontent.com/1148709/57087981-7ab85e80-6cbe-11e9-8a33-6ec24494d209.png">
<img width="551" alt="Screen Shot 2019-05-02 at 9 38 25 AM" src="https://user-images.githubusercontent.com/1148709/57087980-7ab85e80-6cbe-11e9-90bc-ed384ea49a06.png">

**Comment by mooreds** [comment]
This appears the be taken care of, because of the `Authorized JavaScript origins` instructions here: https://fusionauth.io/docs/v1/tech/identity-providers/google 

I looked at the Google credentials interface and didn't see the `Authorized Domains` section. But, could have missed it.

Leaving this open for a few days for @robotdan to weigh in, then I'll close if my surmise is correct.

**Comment by robotdan** [comment]
I think I opened this not knowing if we were missing something in our doc. As long as we can configure a Google IdP with the provided instructions and have it work - then we're good. 

It has been a while since I configured one from scratch, so I wanted to ensure I wasn't relying upon some configuration that has pre-existed our documentation.

**Comment by mooreds** [comment]
Gotcha. Yup, I configured one when I was troubleshooting the zendesk saml instructions.
