### ISSUE TITLE
Proposal: Add FAQ and discuss why FusionAuth is not open-source

### ISSUE THREAD

**Issue by nikos** [FusionAuth/fusionauth-site#7]
From my personal expierence and questions from team mates I would consider that there might be more people interested in a FAQ section on the FusionAuth website. There are so many good blog articles, like https://fusionauth.io/blog/2019/03/06/keycloak-fusionauth-comparison ... it might be worth extracting some facts answering common questions like why is FusionAuth is not open-source, what are the advantages / disadvantages, link to support plans etc.

**Comment by Bugfrog** [comment]
Thanks for adding this @nikos. We are currently working on a site revision to allow visitors to find the information they want quickly, as well as to highlight popular blog posts and pages. Besides the ones you mention above, what info would you list as most essential?

**Comment by nikos** [comment]
Thanks @Bugfrog for coming back to my proposal. Since FusionAuth has a very nice documentation, most questions can be answered there, but maybe you can shed some light into motivation behind product decisions? ... like for example: why is the fulltext-search with Elastic required (esp. when setting up a minimal environment) ?
Also an import guide resp. real-world samples migrating/importing user/group data into FusionAuth would be helpful. Maybe also some more examples regarding how to make use of the password encryptor would help getting started?

**Comment by robotdan** [comment]
Thanks for that feedback @nikos . Perhaps we could add an option in the documentation to ask questions such as that and we can add the most popular ones to an FAQ section. 

In the mean time, here are some brief answers. 

> why is the fulltext-search with Elastic required (esp. when setting up a minimal environment) ?

We built FusionAuth to scale to 100's of millions of users. We've been building a real time filter for user generated content and moderation platform called CleanSpeak for years - so we planned ahead so to speak.  Using a traditional relational database to do full text queries is difficult and not efficient, so we leverage Elasticsearch here instead. 

We have had clients that wish to embed FusionAuth and as such only expect 100's of users and have no need for Elasticsearch. It is possible we will try to more fully support this scenario in the future and make Elasticsearch optional at the trade off of reduced search capability or search performance. 

> Also an import guide resp. real-world samples migrating/importing user/group data into FusionAuth would be helpful. Maybe also some more examples regarding how to make use of the password encryptor would help getting started?

These are all great ideas as well, these items on our list. Please feel free to open feature requests on this `fusionauth-site` project for these types of requests. The squeaky wheel gets the oil. 

The open source choice, this is a longer discussion. The simple answer is that there are pros and cons to making our intellectual property open source. At this point we have chosen a closed source model for the core product but open source many components as well. All of the doc, website, client libraries, jwt library, mvc, domain, etc are open source. 

We continually discuss this strategy internally and evaluate what is best for the longevity and quality of the product. From our perspective there is a misconception that open source equates to longevity. While it is true that anyone could fork and maintain FusionAuth if it was open source, many open source projects die because there is no maintainer. It is also possible that a company such as IBM - that now owns KeyCloak / RedHat could choose to no longer support KeyCloak, or change the source code licensing model. In other words, the licensing model does not necessarily mean it will be supported or properly maintained. 

I understand this is a sensitive topic for many and we do certainly see positive aspects of making the entire platform open source. There are no plans to modify our licensing model - but the future is uncertain. :-)

**Comment by mooreds** [comment]
I added a forum post a while back https://fusionauth.io/community/forum/topic/22/why-isn-t-fusionauth-open-source but will also file a PR to update the license-faq.

**Comment by mooreds** [comment]
This has been deployed and the explanation lives here: https://fusionauth.io/license-faq/#30
